name: MinigamesCore
main: dev.yours4nty.MinigamesCore
version: 1.0.0
api-version: 1.20
commands:
  mg:
    description: Comando principal de MinigamesCore
    usage: /mg
    aliases: [minigame, minigames]
